name: Generate spec
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and upload
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.x"

      # Build it, and make sure no warnings are present.
      - name: Build documentation
        run: ./make.py

      # Run the deployment, for now its on GitHub pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html

