name: CI
on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  ci:
    name: CI

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.x"

      # Build it, and make sure no warnings are present.
      - name: Build documentation
        run: ./make.py

      - name: Install Python dependencies
        run: python3 -m pip install black flake8

      - name: Verify Python code formatting
        run: black . --check --diff --color

      - name: Lint Python code with flake8
        run: flake8 . --exclude .venv
